name: Generate sitemap with lastmod

# Kada se workflow pokreće
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Permissions da workflow može da komituje fajlove
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repoa
      - uses: actions/checkout@v4

      # Instalacija Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Instalira sitemap generator CLI
      - run: npm install -g sitemap-generator-cli

      # Generiše sitemap sa lastmod tagovima
      - run: |
          sitemap-generator https://sandra-putuje.github.io/tamo-daleko \
          --strip-querystring \
          --max-concurrency 5 \
          --lastmod \
          --output ./sitemap.xml

      # Automatski commit-uje i push-uje novi sitemap
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update sitemap with lastmod"
          file_pattern: sitemap.xml
