name: Generate sitemap with lastmod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Instalira Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Instalira sitemap generator koji podržava lastmod
      - run: npm install -g sitemap-generator-cli

      # Generiše sitemap sa lastmod (datum poslednjeg commita za svaki fajl)
      - run: |
          sitemap-generator https://sandra-putuje.github.io/tamo-daleko \
          --strip-querystring \
          --max-concurrency 5 \
          --lastmod \
          --output ./sitemap.xml

      # Automatski komituje novi sitemap
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update sitemap with lastmod"
          file_pattern: sitemap.xml
